---
apiVersion: v1	
kind: Pod
metadata: 
  name: nginx-pod1
  labels:
    environment: dev
    app: nginx
spec:
  containers:
    - name: reddy-pod
      image: nginx:1.25
       ports:
    - containerPort: 80 
---
apiVersion: v1	
kind: Pod
metadata: 
  name: nginx-pod2
  labels:
    environment: qa
    app: nginx
spec:
  containers:
    - name: reddy-pod
      image: nginx:1.25
       ports:
    - containerPort: 80 
---
apiVersion: v1	
kind: Pod
metadata: 
  name: nginx-pod3
  labels:
    environment: uat
    app: nginx
spec:
  containers:
    - name: reddy-pod
      image: nginx:1.25
       ports:
    - containerPort: 80 