---
- name: test something
  hosts: ubuntu
  tasks:
    - name: print something
      ansible.builtin.debug:
        var: name
    - name: print my other variable
      ansible.builtin.debug:
        var: group